### ISSUE TITLE
String class incompatible with PHP7

### ISSUE THREAD

**Issue by thelucre** [BKWLD/php-library#11]
Deploying to a newly minted Arcus server and getting an error. Should be renamed (see: https://github.com/UnionOfRAD/lithium/issues/1205#issuecomment-121196060)

`PHP Fatal error:  Cannot use Bkwld\Library\Utils\String as String because 'String' is a special class name in /storage/av03895/artfolio/staging/releases/20160802045315/vendor/bkwld/decoy/classes/Models/Admin.php on line 6`

**Comment by weotch** [comment]
We should see if any other classes names are invalid in php7 while fixing this. 


- Robert Reinhard

**Comment by weotch** [comment]
@thelucre Here is what you'll need to do in your composer file to make your php-library `dev-master` fulfill Decoy's constraint for `^4.0`: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias
